import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 7
padding.y = 0

decorations = "None"

opacity = 0.9
blur = true

startup_mode = "Fullscreen"

[font]
normal.family = "UbuntuMono Nerd Font"
size = 20

